kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "openshift-pipeline-poc"
spec:
  source:
    git:
      uri: "https://github.com/wasanthag/openshift-pipeline-poc.git"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
